### ISSUE TITLE
Sisältö etusivulle

### ISSUE THREAD

**Issue by sankarimo** [lapsivesinokkaelainlaakari/60v#1]
Kamalan vaikeaa lukea sellaista mitä ei ole näytillä. Tähän oli varmasti jokin ratkaisu.

**Comment by quulah** [comment]
Tosi on.

**Comment by quulah** [comment]
Tein base16 teeman reposta forkin ja muutin sitä niin, että se nyt "Home"-otsikolla merkitty sivu pitäisi näkyä etusivulla.

Lokaalilla Hugo serverillä näyttäisi toimivan, mutta Github ei halua.

**Comment by quulah** [comment]
Nähtävästi se oli tuo public/ hakemiston gh-pages branch, joka ei suostunut päivittymään.

**Comment by quulah** [comment]
https://github.com/X1011/git-directory-deploy

Kaappasin tuolta valmiin deploy-skriptin ja modasin sitä vähän. Osannee nyt tehdä sen CNAMEn.

```
$ hugo -d dist && ./deploy.sh --dns-cname timovirtanenjamiika.kankare.fi
```
